/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/content/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    Header: typeof import('./src/components/header/index.vue')['default']
    Left: typeof import('./src/components/header/left.vue')['default']
    Menu: typeof import('./src/components/header/menu.vue')['default']
    NotData: typeof import('./src/components/not-data/index.vue')['default']
    Right: typeof import('./src/components/header/right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
