# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: docs-build

on:
  push:
    branches: 
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build docs
        run: |
            cd /home/runner/work/develop-utils/develop-utils/docs-site
            pnpm install
            pnpm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: docs # 部署后提交到那个分支
          folder: docs-site/dist # 这里填打包好的目录名称
          target-folder: docs
